package com.cliff.aws.blogen.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.springframework.data.annotation.Id;

import java.time.Instant;
import java.util.Set;

/**
 * Author: Cliff
 */
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
@EqualsAndHashCode(of = {"blogenPrimaryKey"})
@DynamoDBTable(tableName = "Blogen")
public class Blogen {

    // prefix used within the primary range key indicating the item contains user information
    public static final String RANGE_USER = "USER";
    // prefix used within the primary range key indicating the item contains post information
    public static final String RANGE_POST = "POST";
    // prefix used within the primary range key indicating the item contains a user's avatar information
    public static final String RANGE_AVATAR = "AVATAR";
    // prefix used within the primary range key indicating the item contains post category information
    public static final String RANGE_CATEGORY = "CATEGORY";
    // the string used to separate composite keys, this is mainly used within the primary range key
    public static final String ATT_SEP = "_";


    @Id
    private BlogenPrimaryKey blogenPrimaryKey;

    private Instant updatedTimestamp;
    private String userId;
    // userName is the user's preferred username or nickname
    private String userName;

    // user detail attributes
    private String firstName;
    private String lastName;
    private String email;
    private String password;        // password will be encrypted
    private boolean enabled;
    private String avatarFileName;
    private Set<String> roles;

    //post specific attributes
    private String title;
    private String text;
    private String imageUrl;
    private String categoryName;
    private String threadId;
    private String postId;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "rangeIndex")
    public String getPrimaryHash() {
        return blogenPrimaryKey != null ? blogenPrimaryKey.getPrimaryHash() : null;
    }

    public void setPrimaryHash( String userId ) {
        if (blogenPrimaryKey == null) {
            blogenPrimaryKey = new BlogenPrimaryKey();
        }
        blogenPrimaryKey.setPrimaryHash( userId );
    }

    @DynamoDBRangeKey
    @DynamoDBIndexHashKey(globalSecondaryIndexNames = {"rangeIndex"})
    @DynamoDBIndexRangeKey(globalSecondaryIndexNames = {"userIdIndex","categoryNameIndex"} )
    public String getPrimaryRange() {
        return blogenPrimaryKey != null ? blogenPrimaryKey.getPrimaryRange() : null;
    }

    public void setPrimaryRange( String various ) {
        if (blogenPrimaryKey == null) {
            blogenPrimaryKey = new BlogenPrimaryKey();
        }
        blogenPrimaryKey.setPrimaryRange( various );
    }


    @DynamoDBIndexHashKey(globalSecondaryIndexName = "userIdIndex")
    public String getUserId() {
        return userId;
    }
    public void setUserId( String userId ) {
        this.userId = userId;
    }


    public String getUserName() {
        return userName;
    }

    public void setUserName( String userName ) {
        this.userName = userName;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName( String firstName ) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName( String lastName ) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail( String email ) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword( String password ) {
        this.password = password;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled( boolean enabled ) {
        this.enabled = enabled;
    }

    public String getAvatarFileName() {
        return avatarFileName;
    }

    public void setAvatarFileName( String avatarFileName ) {
        this.avatarFileName = avatarFileName;
    }

    public Set<String> getRoles() {
        return roles;
    }

    public void setRoles( Set<String> roles ) {
        this.roles = roles;
    }

    @InstantFormat
    public Instant getUpdatedTimestamp() {
        return updatedTimestamp;
    }

    public void setUpdatedTimestamp( Instant updatedTimestamp ) {
        this.updatedTimestamp = updatedTimestamp;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle( String title ) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText( String text ) {
        this.text = text;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl( String imageUrl ) {
        this.imageUrl = imageUrl;
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "categoryNameIndex")
    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName( String categoryName ) {
        this.categoryName = categoryName;
    }

    public String getThreadId() {
        return threadId;
    }

    public void setThreadId( String threadId ) {
        this.threadId = threadId;
    }

    public String getPostId() {
        return postId;
    }

    public void setPostId( String postId ) {
        this.postId = postId;
    }


    /**
     * build the rangeKey string that is used to identify blogen posts
     * @param created
     * @param postId
     * @return
     */
    public static String buildPostRangeKey( Instant created, String postId ) {
        return Blogen.RANGE_POST + Blogen.ATT_SEP + created.toString() + Blogen.ATT_SEP + postId;
    }
}
