package com.cliff.aws.blogen.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 *  This class is needed by Spring-Data-DynamoDB to model a composite Hash Key and Range Key, so that the Blogen
 *  entity class can be properly persisted into dynamodb using the BlogenRepository
 *
 * This class must implement Serializable if you are using a Spring version less than Spring 5/Spring Data 2.0
 *
 * Author: Cliff
 *
 * @see <a href="https://github.com/derjust/spring-data-dynamodb/wiki/Use-Hash-Range-keys">Spring-Data-DynamoDB</a>
 */
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Data
public class BlogenPrimaryKey {
    //private static final long serialVersionUID = 57L;

    private String primaryHash;
    private String primaryRange;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "rangeIndex")
    public String getPrimaryHash() {
        return primaryHash;
    }

    public void setPrimaryHash( String primaryHash ) {
        this.primaryHash = primaryHash;
    }

    @DynamoDBRangeKey
    @DynamoDBIndexHashKey(globalSecondaryIndexNames = {"rangeIndex"})
    @DynamoDBIndexRangeKey(globalSecondaryIndexNames = {"userIdIndex", "categoryNameIndex"} )
    public String getPrimaryRange() {
        return primaryRange;
    }

    public void setPrimaryRange( String primaryRange ) {
        this.primaryRange = primaryRange;
    }
}
