# AWS CodeBuild buildspec
# this BuildSpec will build the Blogen Lambdas artifact
version: 0.2

phases:
  install:
    commands:
    - echo Nothing to do in the install phase...
  pre_build:
    commands:
    - echo Nothing to do in the pre_build phase...
  build:
    commands:
    - echo Build started on `date`
    - mvn install -pl lambdas
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
  - lambdas/target/blogen-lambdas-0.0.1.jar
  discard-paths: yes